name: base
channels:
  - defaults
  - conda-forge
  - open3d-admin
dependencies:
  - numpy
  - open3d>=0.15.0
  - pandas
  - pip
  - python>=3.9
  - dask
  - nb_conda_kernels
  - plotly
  - plotly-orca
  - ipykernel
  - pandoc
  - pip:
      - fastparquet
      - jupyter
      - nbconvert
      - nbformat
      - rospkg
      - py3rosmsgs
      - pyntcloud
      - setuptools
      - laspy<2.0.0
      - pylas
      - mypy
      - pylint
      - flake8
      - typer
      - nbval
      - geopandas
      - fastparquet
      - pycryptodomex
      - sphinx
      - sphinxcontrib-napoleon
      - sphinx_rtd_theme==0.5.2
      - nbsphinx
      - sphinx-click
prefix: /opt/conda
